apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapp-dev
  namespace: argocd
spec:
  project: dev-project           # use your AppProject
  source:
    repoURL: https://github.com/gititc778/gitops
    targetRevision: master
    path: sampleapp
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapp-stage
  namespace: argocd
spec:
  project: dev-project           # use your AppProject
  source:
    repoURL: https://github.com/gititc778/gitops
    targetRevision: master
    path: sampleapp
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
