apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapp-gitgen
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
            namespace: dev
            name: sampleapp-dev
          - cluster: https://192.168.111.132:8443
            namespace: dev
            name: sampleapp-stage
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/gititc778/gitops
        targetRevision: master
        path: sampleapp
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
