apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapp-listgen
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: sampleapp-list-dev
            namespace: dev
          - name: sampleapp-list-stage
            namespace: stage
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: dev-project
      source:
        repoURL: https://github.com/gititc778/gitops
        targetRevision: master
        path: sampleapp
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
