apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapp-single
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://github.com/gititc778/gitops
    targetRevision: master
    path: sampleapp
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
