apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
spec:
  description: Project for dev and stage environments on the default cluster

  sourceRepos:
    - https://github.com/gititc778/gitops

  destinations:
    - server: https://kubernetes.default.svc
      namespace: dev
    - server: https://kubernetes.default.svc
      namespace: stage

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: ""
      kind: PersistentVolume

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
