apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapp-gitgen
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gititc778/gitops
        revision: master        # <-- change here
        directories:
          - path: sampleapp
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: dev-project
      source:
        repoURL: https://github.com/gititc778/gitops
        targetRevision: master   # <-- change here
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
