apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapp-gitgen
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/gititc778/gitops'
        revision: main          # ✅ updated to your branch
        directories:
          - path: sampleapp
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: dev-project
      source:
        repoURL: 'https://github.com/gititc778/gitops'
        targetRevision: main    # ✅ updated to your branch
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
