apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapp-matrix
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - cluster: https://kubernetes.default.svc
                  namespace: dev
          - list:
              elements:
                - name: sampleapp-dev
                - name: sampleapp-stage
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: dev-project
      source:
        repoURL: https://github.com/gititc778/gitops
        targetRevision: master
        path: sampleapp
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
