apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapp-gitgen
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gititc778/gitops
        revision: master          # 👈 must match your actual Git branch
        directories:
          - path: sampleapp

  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: dev-project

      source:
        repoURL: https://github.com/gititc778/gitops
        targetRevision: master   # 👈 must match your branch
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: dev

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

      ignoreDifferences:
        # Ignore replica drift (manual scaling or HPA)
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas

        # Ignore status fields (managed by Kubernetes)
        - group: "*"
          kind: "*"
          jsonPointers:
            - /status
